export const SKILLS_REQUEST = "SKILLS_REQUEST"
export const SKILLS_REQUEST_FAIL = "SKILLS_REQUEST_FAIL"
export const SKILLS_REQUEST_SUCCESS = "SKILLS_REQUEST_SUCCESS"
export const SKILLS_POST_SUCCESS = "SKILLS_POST_SUCCESS"
