export const DEVELOPER_REQUEST = "DEVELOPER_REQUEST";
export const DEVELOPER_REQUEST_FAIL = "DEVELOPER_REQUEST_FAIL";
export const DEVELOPER_REQUEST_SUCCESS = "DEVELOPER_REQUEST_SUCCESS";

export const DEVELOPER_POST_SUCCESS = "DEVELOPER_POST_SUCCESS";
